version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      runtime-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "winres"
          - "iconwriter"
      build-dependencies:
        patterns:
          - "winres"
          - "iconwriter"
  - package-ecosystem: "cargo"
    directory: "/src/package/"
    schedule:
      interval: "weekly"
    groups:
      packaging-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      automation-dependencies:
        patterns:
          - "*"
