name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
    
    - name: Install toolchain
      run: rustup toolchain install stable --profile minimal
      
    - name: Install dependencies
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt update
        sudo apt install libgtk-3-dev libayatana-appindicator3-dev libxdo-dev
        
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          .
          src/package
          
    - name: Package
      run: cargo run --verbose
      working-directory: src/package
      
    - uses: softprops/action-gh-release@v1
      with:
        files: src/package/*.zip
        fail_on_unmatched_files: true
